---
- name: "Install GitLab"
  hosts: all 
  become: yes

  tasks:
  - name: "Install dependancies"
    yum:
      - curl
      - policycoreutils
      - openssh-server
      - openssh-clients
    state: latest

  - name: "Start/Enable SSH"
    service:
      name: sshd
      state: started
      enabled: yes

  - name: "Set Firewall rules"
    firewalld:
      service: http https
      permanent: yes
      state: enabled

  - name: "Download Gitlab installer"
    git_url: 
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
      dest: /tmp/gitlab_installer.sh
      mode: 0774

  - name: "Run installer"
    shell: /tmp/gitlab_install.sh >> /tmp/gitlab_install.log

